version: 0.2

phases:
  install:
    commands:
      - echo "nothing to install"
  pre_build:
    commands:
      - dotnet restore ./LambdaTestFunc/LambdaTestFunc.csproj
      - dotnet restore ./LambdaTestFunc.Tests/LambdaTestFunc.Tests.csproj
      - dotnet test ./LambdaTestFunc.Tests/LambdaTestFunc.Tests.csproj
  build:
    commands:
      # v1 - not good
      #- cd ./LambdaTestFunc
      #- dotnet lambda deploy-serverless "lambda-test-func-001-stack" -sb $BUILD_OUTPUT_BUCKET
      #- echo deploy completed on `date`

      # v2 - better way
      - cd ./LambdaTestFunc
      - dotnet lambda package-ci --template ../app-sam.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template ../app-sam-output.yaml


      # usefull commands

      #- dotnet publish ./LambdaTestFunc/LambdaTestFunc.csproj --output out/ --configuration Release
      #- cd ./LambdaTestFunc/out
      #- zip ../../package.zip *

      #- aws s3 cp package.zip s3://$BUILD_OUTPUT_BUCKET/package.zip

      #- echo $(ls)

      #- aws cloudformation package --template-file app-sam.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file app-output_sam.yaml
      
      #- dotnet publish ./LambdaTestFunc/LambdaTestFunc.csproj --output out/ --configuration Release
      #- cd ./LambdaTestFunc/out
      #- zip ../../package.zip *

      #- cd ./LambdaTestFunc/out
      #- cd ./LambdaTestFunc
      #- dotnet lambda deploy-function
  post_build:
    commands:
      - echo Build and test completed on `date`

artifacts:
  files:
    - app-sam-output.yaml
    #- transformed.template
    #- package.zip
  discard-paths: yes